app:
  name: "blog"
  mode: "dev"
  port: 9999
  version: "1.0"
  start_time: "2020-07-01"
  machineId: 1

log:
  lever: "debug"
  filename: "blog.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "sql_test"
  max_open_conns: 20
  max_Idle_connss: 10

redis:
  host: "127.0.0.1"
  port: 6379
  password: "123456"
  db: 0
  pool_size: 100